### ISSUE TITLE
Switching from Totalkredit to another institute while having Kundekroner selected breaks the original loan calculation

### ISSUE THREAD

**Issue by Sobuno** [mathiastj/mortgage-refinancer#10]
https://mathiastj.github.io/mortgage-refinancer?principal=2100000&terms_left=27&extra_charge=0.74&interest=1&estimated_price=3400000&other_interest_per_year=0&current_price=74&instalment_free_years_left=0&single=false&church_tax=false&municipality=Albertslund&customer_kroner=false&new_loan_instalment_free=false&current_price_new_loan=95&fees_new_loan=15000&interest_new_loan=4&institute=Realkredit%20Danmark

https://mathiastj.github.io/mortgage-refinancer?principal=2100000&terms_left=27&extra_charge=0.74&interest=1&estimated_price=3400000&other_interest_per_year=0&current_price=74&instalment_free_years_left=0&single=false&church_tax=false&municipality=Albertslund&customer_kroner=true&new_loan_instalment_free=false&current_price_new_loan=95&fees_new_loan=15000&interest_new_loan=4&institute=Realkredit%20Danmark

The only difference in the above two links is that the query param `customer_kroner` is set to true in the second link. The resulting pages are identical, but the calculations are different since Kundekroner is silently applied in the second case, albeit only to the original loan.

An interesting usage scenario is of course if wanting to switch from Totalkredit to a different institute or vice versa, probably need to be able to select both original institute and new institute then.

**Comment by mathiastj** [comment]
This is a good point. I forgot that I applied kundekroner to the original loan as well.

I think the use case of switching institute is too much of an edge case to add yet another form input to support it.
