### ISSUE TITLE
Ekstraordinære afdrag should be supported

### ISSUE THREAD

**Issue by Sobuno** [mathiastj/mortgage-refinancer#13]
Right now, the calculator tells you to subtract the value of an extra payment in the fees field. However, this is wrong as an extra payment should be divided by the original loan's rate to obtain its actual value. 

The fees field is currently just added straight to the new loan, and if #9 is merged, is divided by the new loan's rate to obtain its cost - none of those solutions are correct in terms of extra payments and will thus not reflect their (higher) value correctly.

(I have the modified code ready, but it builds on top of #9, hence no PR yet)

**Comment by mathiastj** [comment]
I don't believe the extra payment should be at the original loan's rate, when you're also doing a refinance. The refinancing can be viewed as one large extra payment, and thus there's no 'extra' left to claim. The extra payment will therefore be at the nominal value before you get the new loan. At least that's my understanding of it, here's an example:

You have a principal of 1.000.000
The price of the current loan is 90
You therefore need to pay 900.000 for the current loan
If you have 100.000 in cash, you only need a loan of 800.000
Let's say the price of the new loan is 95
The principal of the new loan is then ~842.000

Had the price of the new loan been ~100 the principal would be ~800.000.


I see that after merging #9 it is indeed calculated wrongly now. I think I might just remove the wording from the tooltip and possibly add a new field for extra payments.

**Comment by Sobuno** [comment]
Sorry, you are correct :)
