### ISSUE TITLE
newLoanPrice calculation is wrong

### ISSUE THREAD

**Issue by Sobuno** [mathiastj/mortgage-refinancer#8]
https://mathiastj.github.io/mortgage-refinancer?principal=2700000&terms_left=30&extra_charge=0.69&interest=1&estimated_price=3350000&other_interest_per_year=0&current_price=74&instalment_free_years_left=0&single=false&church_tax=true&municipality=Aarhus&customer_kroner=false&new_loan_instalment_free=false&current_price_new_loan=74&fees_new_loan=0&interest_new_loan=1&institute=Realkredit%20Danmark

Maybe I do not understand the math behind it, but how can refinancing this loan to the same loan change the principal by 182k in a (for the consumer) positive direction?

Shouldn't buying the bond at a given rate and then selling them at the exact same rate equal a net difference of 0?

The issue probably lies in the `newLoanPrice` variable in the code. It should simply be calculating the inverse or reciprocal value of the new loan's bond rate, i.e. `1 / (loanInfo.currentPriceNewLoan / 100)` instead of whatever is going on now.

The issue is not huge for values close to 100 as can be seen below, hence why the issue is probably undetected - however refinancing to a loan with a lower rate causes huge calculation issues as mentioned above:

![image](https://github.com/mathiastj/mortgage-refinancer/assets/3593183/bd94d65d-1627-48a9-9d05-2dcae0079b8b)

**Comment by Sobuno** [comment]
`feesNewLoan` should also be affected by the `newLoanPrice` if they are part of the principal of the new loan - otherwise you're not paying the full price.

**Comment by mathiastj** [comment]
> https://mathiastj.github.io/mortgage-refinancer?principal=2700000&terms_left=30&extra_charge=0.69&interest=1&estimated_price=3350000&other_interest_per_year=0&current_price=74&instalment_free_years_left=0&single=false&church_tax=true&municipality=Aarhus&customer_kroner=false&new_loan_instalment_free=false&current_price_new_loan=74&fees_new_loan=0&interest_new_loan=1&institute=Realkredit%20Danmark
> 
> Maybe I do not understand the math behind it, but how can refinancing this loan to the same loan change the principal by 182k in a (for the consumer) positive direction?
> 
> Shouldn't buying the bond at a given rate and then selling them at the exact same rate equal a net difference of 0?
> 
> The issue probably lies in the `newLoanPrice` variable in the code. It should simply be calculating the inverse or reciprocal value of the new loan's bond rate, i.e. `1 / (loanInfo.currentPriceNewLoan / 100)` instead of whatever is going on now.
> 
> The issue is not huge for values close to 100 as can be seen below, hence why the issue is probably undetected - however refinancing to a loan with a lower rate causes huge calculation issues as mentioned above:
> 
> ![image](https://user-images.githubusercontent.com/3593183/256990354-bd94d65d-1627-48a9-9d05-2dcae0079b8b.png)

This is a very good catch! I honestly don't remember where I've gotten the `1+(1-` formula from.

**Comment by mathiastj** [comment]
> `feesNewLoan` should also be affected by the `newLoanPrice` if they are part of the principal of the new loan - otherwise you're not paying the full price.

Also a good point. Since I'm including it in the principal it should be at the price of the new loan.
